controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Contact;
use app\models\ContactForm;
use app\models\Content;
use app\models\LoginForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\SignupForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;


class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only'  => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow'   => true,
						'roles'   => ['@'],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		$content   = Content::find()->orderBy(['created_at' => SORT_DESC])->limit(4)->all();
		$main_page = Content::find()->where(['title' => 'main'])->one();

		return $this->render('index', [
			'content'   => $content,
			'main_page' => $main_page
		]);
	}

	/**
	 * Sign-Up action.
	 *
	 * @return Response|string
	 */

	public function actionSignUp()
	{
		$model = new SignupForm();

		if ($model->load(Yii::$app->request->post()))
		{
			if ($user = $model->signup())
			{
				if (Yii::$app->getUser()->login($user))
				{
					return $this->goHome();
				}
			}
		}

		return $this->render('sign-up', [
			'model' => $model,
		]);
	}

	/**
	 * Login action.
	 *
	 * @return Response|string
	 */
	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest)
		{
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login())
		{
			return $this->goBack();
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	/**
	 * Displays contact page.
	 *
	 * @return Response|string
	 */
	public function actionContact1()
	{
		$model = new ContactForm();
		if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail']))
		{
			Yii::$app->session->setFlash('contactFormSubmitted');

			return $this->refresh();
		}

		return $this->render('contact', [
			'model' => $model,
		]);
	}


	public function actionContact()
	{

		$model = new Contact();

		return $this->render('contact', [
			'model' => $model,
		]);
	}

	public function actionAdmin(){
		return $this->redirect('/admin/');
	}

	public function actionSendEmail()
	{
		Yii::$app->response->format = Response::FORMAT_JSON;

		$response = ['response' => 'not-send'];
		if (isset($_POST['Contact']))
		{
			$model = new Contact();
			$model->load(Yii::$app->request->post());
			$model->created_at = time();
			if ($model->save())
			{
				if ($model->contact('dreammago@gmail.com'))
				{
					$response = ['response' => 'send'];
				}
				else
				{
					$response = ['response' => 'not-send'];

				}
			}
			else
			{
				$response = ['response' => 'not-validate'];
			}
		}

		return $response;
	}

	/**
	 * Requests password reset.
	 *
	 * @return mixed
	 */
	public function actionRequestPasswordReset()
	{
		$model = new PasswordResetRequestForm();

		if ($model->load(Yii::$app->request->post()) && $model->validate())
		{
			if ($model->sendEmail())
			{
				Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

				return $this->goHome();
			}
			else
			{
				Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
			}
		}

		return $this->render('requestPasswordResetToken', [
			'model' => $model,
		]);
	}

	/**
	 * Resets password.
	 *
	 * @param string $token
	 *
	 * @return mixed
	 * @throws BadRequestHttpException
	 */
	public function actionResetPassword($token)
	{
		try
		{
			$model = new ResetPasswordForm($token);
		}
		catch (InvalidParamException $e)
		{
			throw new BadRequestHttpException($e->getMessage());
		}

		if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword())
		{
			Yii::$app->session->setFlash('success', 'New password was saved.');

			return $this->goHome();
		}

		return $this->render('resetPassword', [
			'model' => $model,
		]);
	}


	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout()
	{
		return $this->render('about');
	}
}

views/site/contact.php
<?php
/**
 * Created by PhpStorm.
 * User: evg
 * Date: 29.07.17
 * Time: 16:25
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Pjax;

?>


<body>
<div id="fh5co-page">
    <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
	<?= $this->context->renderPartial('/layouts/menu', ['page_url' => 'index']) ?>


    <div id="fh5co-main">
        <div class="fh5co-narrow-content animate-box" data-animate-effect="fadeInLeft">
            <div class="row">
                <h1>Мои контакты</h1>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h2><?= Html::a('Skype:', 'skype:barsiksookamordiy'); ?> barsiksookamordiy </h2>
                </div>
                <div class="col-md-6">
                    <h2><?= Html::a('Email', 'mailto:evgeny@rudakov.site'); ?>: evgeny@rudakov.site </h2>
                </div>
                <div class="col-md-6">
                    <h2><?= Html::a('Gmail', 'mailto:dreammago@gmail.com'); ?>: dreammago@gmail.com </h2>
                </div>
                <div class="col-md-6">
                    <h2><?= Html::a('VK', 'https://vk.com/sookamordiy', ['target' => '_blank']); ?>: Евгений
                        Рудаков</h2>
                </div>
            </div>


            <div class="row">
                <h1>Написать мне</h1>
            </div>
            <div class="js-add-ajax-responce"></div>


			<?php
			$form = ActiveForm::begin([
				'options' => [
					'class' => 'contact-form'
				]
			]);
			?>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
							<?= $form->field($model, 'name')->textInput(['placeholder' => 'Имя'])->label(false) ?>
							<?= $form->field($model, 'email')->textInput(['placeholder' => 'Email'])->label(false) ?>
							<?= $form->field($model, 'phone')->label(false)->widget(\yii\widgets\MaskedInput::className(), [
								'mask'          => '+7 (999) 999 99 99',
								'options'       => [
									'class'       => 'form-control',
									'placeholder' => 'Телефон',
								],
								'clientOptions' => [
									'clearIncomplete' => true
								]
							]); ?>
                        </div>
                        <div class="col-md-6">
							<?= $form->field($model, 'text')->textarea([
								'placeholder' => 'Сообщение',
								'cols'        => 30,
								'rows'        => 4
							])->label(false) ?>

                            <div class="form-group">
								<?= Html::button('Отправить', ['class' => 'btn btn-primary btn-md js-send-form-button']) ?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
			<?php
			ActiveForm::end();
			?>

        </div>
    </div>
</div>
<?php
$send_form = <<<JS
$('#fh5co-page').on('click','.js-send-form-button', function() {
$('.js-send-form-button').prop('disabled',true);
$.ajax({
    url:'/site/send-email',
    method:'post',
    dataType: 'json',
    data:{
        Contact:{
            'name':$('#contact-name').val(),
            'email':$('#contact-email').val(),
            'phone':$('#contact-phone').val(),
            'text':$('#contact-text').val()
        }
    },
    success: function(data) {
        if (data.response=='send'){
            $('.col-md-6 input').val('');
            $('.col-md-6 textarea').val('');
            var html_message = '<div id="w1-success" style="display:none"  class="alert-success alert fade in">'+
                               '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>'+
                               '<i class="icon fa fa-check"></i>Спасибо за обращение!'+
            '</div>';
            $('.js-add-ajax-responce').html(html_message);
            $('#w1-success').show('slow');
            $('.js-send-form-button').prop('disabled',false);


            
        } else if (data.response=='not-send') {
            html_message = '<div style="display:none" id="w1-error" class="alert-danger alert fade in">'+
                               '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>'+
                               '<i class="icon fa fa-check"></i>Простите, с почтовым сервисом что-то пошло не так.'+
                               'Свяжитесь со мной иначе</div>';
            $('.js-add-ajax-responce').html(html_message);
            $('#w1-error').show('slow');
            $('.js-send-form-button').prop('disabled',false);

        } else  {
            html_message = '<div style="display:none" id="w1-warning" class="alert-warning alert fade in">'+
                               '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>'+
                               '<i class="icon fa fa-check"></i>Без введеных данных почтовый голубь не сможет доставить письмо.' +
                                '</div>';
            $('.js-add-ajax-responce').html(html_message);
            $('#w1-warning').show('slow');
            $('.js-send-form-button').prop('disabled',false);
        }
    }
  });
});
JS;
$this->registerJs($send_form, yii\web\View::POS_READY);


?>

views/site/contact1.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>


        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Rudakov.site';
use app\components\renderContentView;

?>

<div id="fh5co-page">
    <a href="/" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
    <?= $this->context->renderPartial('/layouts/menu',['page_url'=>'index']) ?>

    <div id="fh5co-main">
        <div class="main-page-content fh5co-narrow-content col-md-11 animate-box fadeInLeft animated">
        <?=$main_page->content?>

        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/passwordResetRequestForm.php
<?php
/**
 * Created by PhpStorm.
 * User: evg
 * Date: 10.07.17
 * Time: 13:06
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please fill out your email. A link to reset password will be sent there.</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/site/resetPasswordForm.php
<?php
/**
 * Created by PhpStorm.
 * User: evg
 * Date: 10.07.17
 * Time: 13:07
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please choose your new password:</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/site/sign-up.php
<?php
/**
 * Created by PhpStorm.
 * User: evg
 * Date: 10.07.17
 * Time: 12:43
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please fill out the following fields to signup:</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>